### ISSUE TITLE
[lcc_members] Champs sans titre

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#10]
![image](https://user-images.githubusercontent.com/1217968/76198000-7669a580-61ed-11ea-8c3e-189fe3d9fe96.png)
Ce champs ne contient pas de titre. Quand j'ouvre la liste déroulante, ça ressemble à la liste ds comptes.

**Comment by njeudy** [comment]
Ceci ne concerne pas la nouvelle version adhérent.
