### ISSUE TITLE
[lcc_member] Hide membership notebook page for contacts with parent_id

### ISSUE THREAD

**Issue by stephansainleger** [Lokavaluto/lokavaluto-addons#102]
In Odoo for LCC, we need to differentiate the contacts who are employees or volunteer of an organization which is a LCC member, and the contact who are members on their own.

For instance, if Alfred is a member of the LCC, and employee of a company also member of the LCC, then he should have 2 contact entries on Odoo : 
- one for himself
- one with his company as parent_id (which will later allow him to access to the LCC company wallet)

In order to prevent bad operation like the addition of a membership invoice to a contact entry linked with a company (whereas it should be linked to the company itself, or to a contact entry not linked to a company), I propose to hide the page "Membership" in the contact form view (and the lcc_member form view) **if the contact has a parent_id registered**. In that way it becomes impossible to register a subscription for this contact entry.

**Comment by njeudy** [comment]
hum think we have to define this because actually this is not the way odoo work. If a guy is member one is own, he has an entry in contact which is not linked to a company.

**Comment by stephansainleger** [comment]
Done in https://github.com/Lokavaluto/lokavaluto-addons/pull/110
