### ISSUE TITLE
[lcc_members] bulles d'aide (bouton ajouter)

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#11]
Quand je crée un contact , j'ai un bouton ajouter en bas la page dans l'onglet des adresses et qui concerne les adresses :
voir gif : http://recordit.co/ES27i10UNi

**Comment by njeudy** [comment]
Je ne suis pas sur que cette demande concerne la nouvelle version adhérent.

**Comment by r3dius** [comment]
@njeudy si ! Il existe aussi dans le module adhérent. Mon issue concerne le bloc en popin qui affiche du code au moment on survole ce bouton ajouter et d'ailleurs d'autres éléments de l'interface odoo. Pas compréhensible pour l'user final.
Issue à réouvrir
