### ISSUE TITLE
[lcc_members] ajout bulle d'aide

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#13]
![image](https://user-images.githubusercontent.com/1217968/76200491-04e02600-61f2-11ea-8a2d-6bd591e704aa.png)

**Comment by njeudy** [comment]
Tu peux préciser les demande, je ne vois pas de question.

**Comment by njeudy** [comment]
Ceci ne concerne pas la nouvelle application adhérent.

**Comment by r3dius** [comment]
@njeudy 
Oui sorry! en fait l'idée et d'ajouter une bulle d'aide pour rediriger vers la vidéos qui a été faite par JC.
