### ISSUE TITLE
[lcc members] indisplay company_registry field in res_partner form view

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#138]
No one is using this field

**Comment by MatSarr** [comment]
RCS 
![image](https://user-images.githubusercontent.com/46820746/157807619-d20c0861-902e-4d21-b2d1-3111af677ddc.png)

**Comment by stephansainleger** [comment]
Invalid demand, this field is not added by lcc addons, but by l10n_fr_siret, which is independant from our dev.

**Comment by MatSarr** [comment]
yes but it doesn't mean it's not possible to hide it :) in lcc_members
