### ISSUE TITLE
[lcc_members] visibilité des articles d'adhésion

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#14]
Est-ce que les articles d'adhésion sont cloisonné par société. Est ce qu'un user qui appartenant à une société A peut-il voir les articles d'adhésion d'une entité B ? 
En gros, est ce que les articles sont filtré par société dans toute l'instance odoo laroue.
j'ai pas pu créer user de test vu que les emails son désactivé sur staging.

**Comment by njeudy** [comment]
Tu peux créer un user test en modifiant sont mot de passe directement via le menu action.

**Comment by r3dius** [comment]
Thnx @njeudy . Following the last meeting , we discussed about creating a news work group around rights and accesses. Is it necessary to spend time testing this in staging's version? 
Thnx.
