### ISSUE TITLE
[lcc members] add relations menu in members menu app

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#144]
It would be great to have the relations menu in the members app menu like in contacts:
![image](https://user-images.githubusercontent.com/46820746/155485007-74aa8af2-dc5e-49c2-b3e9-1c81addb7adb.png)

because the relations are mainly used for members

**Comment by stephansainleger** [comment]
Sorry @MatSarr  but I disagree on this one. Today the lcc_members module doesn't need partner_relation module to be installed. If we add this menu, we need to add one more dependency for another module, which makes the module bigger, whereas this menu can be added manually for the LCC which need it.

**Comment by njeudy** [comment]
we need to create a small lcc_member_relation glue module in this case

**Comment by stephansainleger** [comment]
I agree with this idea, because in addition on this module, I wouldn't be surprised to see future needs from LCC on the module partner_relations, like the drawing of networks, KPIs, and so on.
