### ISSUE TITLE
[lcc_members] [Article] A quoi servent ces champs ?

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#15]
![image](https://user-images.githubusercontent.com/1217968/76202129-a5cfe080-61f4-11ea-82d0-274f9138d4ad.png)

**Comment by njeudy** [comment]
Bonjour,

Le champs sont des champs odoo natif:

- compte de revenu = paramètrage comptable lié au produit d'adhésion
- Description vente =  description affichée sur le devis, ou la facture de vente.

Cette  issue n'est pas lié à ce module. Merci de le remonter dans le support lié à votre monnaie locale.
