### ISSUE TITLE
[lcc members portal] fix bug of user mail not change from portal

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#151]
Lorsqu'on change son adresse email depuis les préférences utilisateur portal ça change uniquement l'adresse email de la fiche contact et non du compte utilisateur. Je ne comprends pas qu'on ne puisse pas changer son adresse email et son mdp quand on est un utilisateur portail.

pour 10€ on a ce module qui est en licence LGPL-3 : https://apps.odoo.com/apps/modules/12.0/se_website_change_password/

Point de vigilance: il faut qu'on voit si le changement de l'email de Odoo ne pose pas de pb par rapport au SSO : le changement de mail dans Odoo ne génère pas de changements dans Rocketchat ou Nextcloud, du coup est-ce que le matching des comptes fonctionne toujours ?

**Comment by njeudy** [comment]
En fait l'email de la fiche utilisateur c'est le champs login (et pas le champ mail) c'est juste une traduction .. dans odoo on n'est pas obligé d'avoir un email comme login .. (genre par exemple le compte admin). Donc c'est un comportement normal .. concernant le mot de passe ca permet d'avoir une confirmation par email et du coup d'utiliser tout le temps j'ai oublié mon mot de passe .. on pourrait y ajouter une solution Opensource, à voir le besoin ..

**Comment by stephansainleger** [comment]
**Proposition :** rajouter dans la page /my/account un champ login afin que l'utilisateur change son login. 
Afin de s'assurer que le process de récupération de mdp fonctionne, on met une vérification pour obliger à ce que ce champ soit un mail (`widget="email"`)

**Comment by stephansainleger** [comment]
Autre proposition : coder un process qui met à jour le login en lui donnant la valeur de l'email : quand la personne change son email, ça changera : 
 - l'email dans la fiche partner principale
 - le login dans le user

**Comment by MatSarr** [comment]
Testé sur demo.lokavaluto (après MAJ des modules membres et portal) --> non fonctionnel. Je change mon adresse depuis le portail en cliquant sur "modifier mon compte" la nouvelle adresse email s'affiche, mais c'est toujours l'ancienne qui me permet de me connecter et qui est prise en compte comme login.

**Comment by MatSarr** [comment]
pb de MAJ réglé sur demo.lokavaluto.fr --> le changement d'email = changement de login. C'est tout bon
