### ISSUE TITLE
[lcc_members] translations

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#16]
![image](https://user-images.githubusercontent.com/1217968/76204190-34922c80-61f8-11ea-8892-9de70fb8a5e9.png)
Some words are not translated in french languages like members and membership products(configuration menu)

**Comment by r3dius** [comment]
It's all good for me. @jcleonard2018 , Do you need to recheck or could I close this request ? (@njeudy  : Shoud l Put a specific tag on in this step of the process ?

**Comment by jcleonard2018** [comment]
J'ai vérifié les traducations qui ont été réalisée dans un autre ticket. 
Il ne reste que "Misc Contacts" qui vient d'un autre module communautaire permettant de gérer les réseaux sociaux illimités.
