### ISSUE TITLE
[lcc_members] make team_id field mandatory in res.partner form view

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#171]

**Comment by stephansainleger** [comment]
Solution must be changed: it is not a good idea to make the field mandatory in the res.partner form view, as lot of partners can have no team_id.
The importance of having a local group is for membership only, then the new solution proposed is to :
- set the team_id field optional again in res.partner form view
- add a team_id mandatory field in the membership registration wizard: if a membership is registered, we have to set a team-id
- ensure that the team_id field is filled if the `free_member` field is checked

**Comment by stephansainleger** [comment]
It is urgent to remove the mandatory attribute of this field, as it prevents any change in the public or position profiles in which the field is not displayed...

**Comment by MatSarr** [comment]
Even if local group is field, it's empty when a membership is registered. 
I'm not satisfied with that.

**Comment by stephansainleger** [comment]
Fix delivered https://github.com/Lokavaluto/lokavaluto-addons/pull/207/commits/42f10d0fbaf86460b4ec7de93307e1ed74973665
