### ISSUE TITLE
[lcc_members] add quick filter "Mes groupes locaux" in members filter view

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#172]
![image](https://user-images.githubusercontent.com/46820746/157900739-59ac6e5a-f9ec-430f-ba16-70c75e49b52b.png)

**Comment by njeudy** [comment]
How do you define "mes groupes locaux" ? crm team I follow ?

**Comment by MatSarr** [comment]
I guess it's the crm team where I am, it you who develop that ^^
But it's know okay
