### ISSUE TITLE
[lcc_members] when account credit, the word "invoice" should be replace by "receipt" in the pdf generated

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#173]
- the word "invoice" should be replace by "receipt" for credit of account (crédit du compte)
- the word "invoice" should be replace by "receipt" for debit of account (reconversion)
- If there is a conversion tax, the word "invoice" is ok
- the word "invoice" should be replace by "receipt" for membership

**Comment by njeudy** [comment]
Hello, I implement this in a new module l10n_fr_lcc_member that add some custom default config and adapt to a french use of lcc addons.

I add a boolean on `account.journal` model and if this is checked invoice will be replace by receipt.

![2022-05-09_15h34_33](https://user-images.githubusercontent.com/995787/167421557-2a9a31f0-20f0-44bb-93d7-4c9b0cfc1753.png)

![2022-05-09_15h38_02](https://user-images.githubusercontent.com/995787/167422256-d03e214d-01b9-44a6-9dd4-14b8c0573aa0.png)

**Comment by MatSarr** [comment]
sounds good
