### ISSUE TITLE
[lcc_comchain_base] proper comchain new account registering seems broken

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/lokavaluto-addons#182]
After merge with new version of `lcc_members`, it seems that creation of accounts are not registered properly anymore.
After checking requests, the informations are sent to odoo, but are not saved.

**Comment by stephansainleger** [comment]
From what I have tested, the issue now is that the new wallet is registered in Odoo, but the status in undefined (should be `to_confirm` ). Then the wallet is not returned in the list of wallet to validate from the admin account.
