### ISSUE TITLE
[lcc_portal] size of left collum not as it should be

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#193]
Size planned:
![image](https://user-images.githubusercontent.com/46820746/164064532-069eca21-3ded-4340-a5e6-ed2f8adcf4f8.png)

Size when installing:
![image](https://user-images.githubusercontent.com/46820746/164064487-a3608ec9-24e5-45fc-aaea-212ad87095bd.png)

**Comment by stephansainleger** [comment]
Oh I forgot to tell you: I did not manage to modify the size of the column through an inherited view, then for now we can only modify the size by updating it in live.
