### ISSUE TITLE
[lcc_members] 'Payer une cotisation' button

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#20]
When i click on the button 'Payer une cotisation' It redirects me to rendez vous page. 
Maybe it's the right behaviour but i'm not sure.
http://recordit.co/B6X4ktqjO0

**Comment by jcleonard2018** [comment]
This bug is important. It seems action ID change depending on the Odoo_member module installation.
Is it possible to get this action ID at the lcc_members installation
