### ISSUE TITLE
[lcc_members] public profil and position profil are displayed in many2many fields

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#216]
example:
create a new meeting, search for a name to add a person, all profil of the person are showing, and it's not possible to tel which one is the main one...

**Comment by njeudy** [comment]
ok thanks, will try to reproduce

**Comment by njeudy** [comment]
create an inherited view for `calendar.view_calendar_event_form`

```
<field name="partner_ids" position="attributes">
  <attribute name="domain">[('is_main_profile','=',True)]</attribute>
</field>
```
done in **https://gestion.laroue.org**
