### ISSUE TITLE
[lcc_members] Carte vierge list view

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#27]
the column 'Etiquette' of carte vierge's page displays numbers of tags and not titles.

**Comment by r3dius** [comment]
KO

**Comment by jcleonard2018** [comment]
@njeudy , 
J'ai l'impression que comme il y avait une étiquette 1 sur les comptoirs de change, le filtre fonctionne mais il faudrait changer l'étiquette.
J'ai peur que ça pose problème avec la Roue. Qu'en penses-tu?
As tu fait la modification pour que l'etiquette soit automatiquement crée à l'installation?

**Comment by jcleonard2018** [comment]
lié à #25

**Comment by njeudy** [comment]
![2021-03-01_22h10_17](https://user-images.githubusercontent.com/995787/109559442-f3ff8300-7ada-11eb-8ee4-fdcb7b2a3cf3.png)
