### ISSUE TITLE
[lcc_members] a lot of fields!

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#28]
Question  : 
Do LCC's users need all theses fields : 
![image](https://user-images.githubusercontent.com/1217968/76580326-d69f6680-64cf-11ea-8aa4-2812f4100185.png)
I think the less field we have , the less users will be lost in odoo universe. 
And this issue does not concern just the sales modules but future ones that can be added to LCC instance of odoo. 
Thanks.

**Comment by jcleonard2018** [comment]
Some pages will not appear depending on right. I think we ca add a check on this when we will work on right managment V2.
At this time i have checked that accounting page is not dispayed if the user don't have right

**Comment by MatSarr** [comment]
Not need anymore
