### ISSUE TITLE
[lcc_members] Articles : société field is not filtred

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#31]
Case : user affected to all companies expect SEVE84. 
When I edit a product , i can affect an article to SEVE84. 
Profil : Reda BOUCID
Expected Behaviour : SEVE84 must'nt appear.

Reda.

**Comment by jcleonard2018** [comment]
Not linked to lcc-members or lokavaluto-addons. To déclare on odoo or OCA

**Comment by r3dius** [comment]
It's not a filter to setup in 'société' field ?

**Comment by njeudy** [comment]
In fact it's a param for odoo instance, you can share product or not between company. It's not affected to lcc_member
