### ISSUE TITLE
[lcc_members] free member 

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#32]
A member with a valid cotisation can not also be a free member ! 
![image](https://user-images.githubusercontent.com/1217968/77560696-15fd8800-6ebe-11ea-830c-6fd9e3de5671.png)

**Comment by jcleonard2018** [comment]
It is not the way it works at this time. 
We could be more explicite. "free member" equal member having payed before migration or membre not having to pay membership

**Comment by r3dius** [comment]
And is it possible to add something to clarify this change on the interface ? thnx.

**Comment by jcleonard2018** [comment]
Reda, 
Following our exchange. Are you ok to close this issue.

**Comment by njeudy** [comment]
free members can be honor member that does not pay for this ..
