### ISSUE TITLE
[lcc_members]Deleting a no invoiced contact

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#34]
![image](https://user-images.githubusercontent.com/1217968/77562170-f23b4180-6ebf-11ea-9a6f-631fe575f484.png)

While the invoice is not validated , I should have the right to delete my contact

**Comment by jcleonard2018** [comment]
As soon as you have an accounting opération you can not delete a user. For me, and for odoo, it is logical.
