### ISSUE TITLE
[lcc_members] Members : field membership KO - losing status

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#35]
Steps to reproduce : 

- Create a contact, 
- Create a invoice,
- Valid the invoice,
- Edit the contact from the member form, 
- Check "Membre libre" -> the membership status change to "Membre libre "
- Uncheck "Membre libre" -> the membership status change to "Non membre "!!!
- Save the contact -> the membership status is lost !

**Comment by jcleonard2018** [comment]
If Have done a chak. After having saved the contact, the status is updated du "membre payant" form me it'is ok

**Comment by r3dius** [comment]
@jcleonard2018 https://recordit.co/RSjNZAFWTu here is a video to help reproducing this bug. Thnx. I added this to to the task in odoo.
