### ISSUE TITLE
[lcc_members] Invoice preview : translate status 

### ISSUE THREAD

**Issue by r3dius** [Lokavaluto/lokavaluto-addons#36]
![image](https://user-images.githubusercontent.com/1217968/77563826-11d36980-6ec2-11ea-8aea-2364aaef853a.png)
![image](https://user-images.githubusercontent.com/1217968/77563944-41827180-6ec2-11ea-9e45-7e7c576992c1.png)

**Comment by jcleonard2018** [comment]
Not linked with lcc-members module
