### ISSUE TITLE
Any documentation ? 

### ISSUE THREAD

**Issue by Virgile-Dauge** [Lokavaluto/lokavaluto-addons#43]
I may have missed it, but I'm not able to find any documentation. 

It would be great to have at least the description of the proposed modules, and even better to have a `how to use` section in the readme.

**Comment by njeudy** [comment]
Hello, that's un our todo list, and doc project will start soon :) you can go to https://lokavaluto.fr to have more info, or joind https://chat.lokavaluto.fr for now :) thanks,
