### ISSUE TITLE
Add "description" Field

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#55]
LCC users must be able to add a detailed description of professionals members

**Comment by jcleonard2018** [comment]
Two description were planned. One in the member record (synthesis) and the detailed description on the web site.
May be we have to decide another way to work

**Comment by njeudy** [comment]
think the website partner page could be enough for detailled description, we need to make a clean template for it.  @MatSarr i close this one , feel free to reopen if you thing `website_description` field is not enough for your need
