### ISSUE TITLE
Add "exchange counter" filed

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#56]
So far, users use a tag to know which contact is an exchange counter. It would be better to have a dedicate field. it would also facilitate gogocarto export

**Comment by jcleonard2018** [comment]
> So far, users use a tag to know which contact is an exchange counter. It would be better to have a dedicate field. it would also facilitate gogocarto export

Exchange counter is a tag at this time to simplify Search. Impact is not null if we create a field.

**Comment by MatSarr** [comment]
actually I just noticed that the field is already created but not displayed

**Comment by njeudy** [comment]
![2021-03-01_21h50_23](https://user-images.githubusercontent.com/995787/109557286-2e1b5580-7ad8-11eb-8549-e83249c11b9a.png)
