### ISSUE TITLE
[Member] Discussion on "Local Group" and "Region" (Bassin vs Groupe local)

### ISSUE THREAD

**Issue by jcleonard2018** [Lokavaluto/lokavaluto-addons#59]
Discussing with Yves form La Cigogne, I have identify 2 notions:
- The local group (Groupe locale) : A group of person promoting the money localy. This notion is already managed in member module as a specific property
- The region : A tag identifying an area or a place grouping some people using the money.
Yves used the region field to manage this. There is a risk of mix with nation region list (Ile de France, Alsace,...)

The question is : 
How to manage Region such as "Area" or "neighbourhood" in member modul

**Comment by njeudy** [comment]
Hello, for me it a spécifique needs so add `lcc_region` field for now ?

**Comment by jcleonard2018** [comment]
Example of local group : Groupe Haut Jura, Groupe Besançon
Example of région : quartier battant, Com Com Saint Claude Haut Jura At this time Region = Alsace, BFC, Bretagne...

**Comment by njeudy** [comment]
For région, we can not change; this is region like in France. Quartier battant is not a region ...
For local group there is a field (team_id) and think it's good, so for me what is missing is Quartier battant or like this ?

So for this à recommand using the res.partner.relation, or créate tags with parent = Area ? I have not enough need to create à new field .. I close this feel free to reopen
