### ISSUE TITLE
[lcc_member] Change/Add the opening_time field

### ISSUE THREAD

**Issue by CedricHerzog** [Lokavaluto/lokavaluto-addons#60]
For now, the only way to get the opening time is by using the field 'opening_time'.
This field is a text type.

We could add a new field related to a new Model containing all the information about the opening time.

**Comment by jcleonard2018** [comment]
Voici l'interface de google.
![image](https://user-images.githubusercontent.com/39128793/109825608-47d4ae00-7c3a-11eb-8305-a2a6adb86cca.png)
De tête ce type d'interface ne gère pas tous les cas:
- Horaires pour des activités itinérantes
- ouverture le dimanche
- Spécificité d'une semaine sur l'autre.
A l'inverse la solution actuelle ne permet pas de dire si le pro est ouvert là maintenant.
Il pourrait être intéressant d'avoir les deux et de pouvoir mettre en plus le texte libre

**Comment by CedricHerzog** [comment]
Pour l'instant les horaires sont renseignées à la main dans un champs texte.
Sauf que selon la personne qui renseigne les données, la forme n'est pas la même.
Une personne pourra écrire ```Mercredi : 09h - 20h``` et une autre ```mercredi - de 9h à 20h```.
L'idée c'est d'avoir un formulaire comme celui proposés par Jean-Christophe pour uniformiser tout ça.
Je pense qu'une ligne par jour avec les horaires du matin et de l'après-midi/soir peut être pas mal.
 
 Voilà un exemple concret de ce que l'on a en base.
![Screenshot 2021-03-06 at 18 28 41](https://user-images.githubusercontent.com/6296846/110215420-ffbbc280-7ea9-11eb-9a40-c10aa9eef119.png)

Attention, il peut y avoir des cas où le membre propose plusieurs services avec des horaires différentes comme dans l'exemple ci dessous.

![Screenshot 2021-03-06 at 18 28 19](https://user-images.githubusercontent.com/6296846/110215418-fc283b80-7ea9-11eb-92d6-56d2a973831e.png)

Dans ce cas là il faudrait faire un formulaire par service avec avec le titre du service auquel il est lié.

Pour l'instant je n'ai pas connaissance dans notre base de magasin avec des horaires un peu exotiques comme une ouverture un mercredi sur 2 le 1er mercredi de chaque mois.

**Comment by njeudy** [comment]
Ok ben je pense qu'il faut demander au autres MLC savoir ce qui peut convenir à tous, car la ca me semble ajouter de la complexite et je pense que du coup le champs texte est le mieux .. c'est plus souple du coup et on met ce qu'on veux ..

**Comment by MatSarr** [comment]
Actual field is ok pour lokavaluto LCC
