### ISSUE TITLE
Add memo to warn about extra image size

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#70]
In La Roue Odoo, we noticed that users add extra images without think about their size. Consequences : they add too much or too bug images and then it's impossible to charge the odoo page (too long to load --> server disconnection)

**A quick solved would be to add the following sentence :** 
_Attention : odoo ne compresse pas les images. la somme totale de vos images ne doit pas dépasser 4mo. Pour compresser vos images vous pouvez par exemple utilsier ce site : https://compressjpeg.com/fr/_

**Comment by njeudy** [comment]
@MatSarr can you explain where do you want to add this sentence ?

**Comment by MatSarr** [comment]
just underneath images suplémentaires
![image](https://user-images.githubusercontent.com/46820746/116231953-cb51dd80-a759-11eb-97dd-b0637b8c7211.png)

**Comment by njeudy** [comment]
![2021-06-01_19h55_12](https://user-images.githubusercontent.com/995787/120369248-4a1ad700-c313-11eb-9ff1-9c4b43346ca3.png)

Code modifier génération de l'image en cours.
