### ISSUE TITLE
[lcc members] add description tab with website_description field

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#74]
![image](https://user-images.githubusercontent.com/46820746/118618864-5441bf00-b7c4-11eb-9a0c-78223234a28f.png)

`<xpath expr="//page[@name='annuaire']" position="after">
   <page name="description" string="Description" attrs="{'invisible': [('is_company','=',False)]}">
      <field name="website_description" placeholder="Description détaillée du professionnel"/>
   </page>
</xpath>`

**Comment by njeudy** [comment]
You can not have a placeholder on html field, what is you need ?

**Comment by MatSarr** [comment]
Already an issue for that
