### ISSUE TITLE
[lcc members]  add and display newsletter field

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#76]
![image](https://user-images.githubusercontent.com/46820746/118619464-e8138b00-b7c4-11eb-9fbf-fe892b421693.png)

`    
<xpath expr="//field[@name='category_id']" position="after">
  <field name="x_newsletter"/> 
</xpath> `

**Comment by njeudy** [comment]
Odoo has already a mechanism to track and unsubcribe from newsletter / mailing list, and track this per diffrent newsletter .. think this is not a way to do, use odoo mecanism for this.

can you explain your need ?

**Comment by MatSarr** [comment]
People who subscribe to local currency from paper have a checkbox "accept to receive newsletter" local currencies asked me to add this field in odoo to know who accepted and add this field in the dynamic newsletter settings.
This field is important only for the beginning, later if the person unsubscribe it's not a problem.

**Comment by njeudy** [comment]
For me it's not a field, if partner subscribe to newsletter he accept to receive newsletter .. in odoo you can manager many newsletter not only one. and with RGPD peope can unscuscribe directly .. so, if  this checkbox is checked on paper, you have to subscribe partner to the newsletter.
