### ISSUE TITLE
[lcc members] add and display market field

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#77]
![image](https://user-images.githubusercontent.com/46820746/118619582-037e9600-b7c5-11eb-91a7-a284c9fd7038.png)

`    
<xpath expr="//field[@name='is_volunteer']" position="after">
  <field name="x_market" attrs="{'invisible': [('is_company','=',False)]}"/> 
</xpath>`

**Comment by njeudy** [comment]
What is the need for this checkbox ? res.partner model become e complexe one with many field to add.

Think you can use tags, or industry_id, or second_industry_ids for this ? could you explain the need?

**Comment by MatSarr** [comment]
cf https://carte.laroue.org/ request from several MLCC (not only la Roue)

**Comment by MatSarr** [comment]
will be added on the odoo of the lcc if needed
