### ISSUE TITLE
[lcc members] add and display partner field

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#78]
![image](https://user-images.githubusercontent.com/46820746/118619806-332d9e00-b7c5-11eb-86a2-dba44d4bf70d.png)

```
   <!-- add partner field -->
<xpath expr="//field[@name='category_id']" position="after">
  <field name="x_partner" attrs="{'invisible': [('is_company','=',False)]}"/> 
</xpath> 
```

**Comment by njeudy** [comment]
Don't understand the need for this too .. can you explain ?

**Comment by MatSarr** [comment]
cf https://carte.laroue.org/ request from several MLCC (not only la Roue)

**Comment by njeudy** [comment]
Could you explain what is partner field ?
