### ISSUE TITLE
[lcc members]  add and display no mlc payement field

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#79]
![image](https://user-images.githubusercontent.com/46820746/118620004-64a66980-b7c5-11eb-8643-bec83af05a86.png)

`   
<xpath expr="//field[@name='x_partner']" position="after">
  <field name="x_no_mlc_payment" attrs="{'invisible': [('is_company','=',False)]}"/> 
</xpath> `

**Comment by njeudy** [comment]
don't understand the need and is specific to agnel ? could you explain the need for this field .. what is the use ? how to make it generic ?

**Comment by MatSarr** [comment]
cf https://carte.laroue.org/ request from several MLCC (not only la Roue and l'Agnel)

**Comment by MatSarr** [comment]
will be added on the odoo of the lcc if needed
