### ISSUE TITLE
[lcc members] display relations and emailling number

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-addons#80]
![image](https://user-images.githubusercontent.com/46820746/118621997-30cc4380-b7c7-11eb-9f9d-f579e349fd88.png)

in order to remove the contact view to keep only the member view, il would be great to add those 3 buttons in the member view

**Comment by njeudy** [comment]
remove the member view ? what is your need, member view is only for members partner, contact view is for all the rest (partners, supplier, contact, email, etc ..) it's two differente case and way to use.

If we add this to member view we need to make lcc_member depends of `partner_multi_relation` and `mass_mailing_partner` and `mass_mailing_list_dynamic` . Is this ok ?

**Comment by MatSarr** [comment]
We had a discussion on RC about merging contacts and members, it's a real request from all the MLCC.
Stéphan et me agreed. We don't feel comfortable with the actual user experience.
But I reckon we should have a talk to define "merging" and choose the best options :)

**Comment by njeudy** [comment]
Ok will add  lcc_member_mass_mailing and lcc_membeer_relation that do the job on member form view

**Comment by MatSarr** [comment]
not needed anymore with lcc members v3
