### ISSUE TITLE
[lcc_lokavaluto_app_connection] partner_map add categories option

### ISSUE THREAD

**Issue by farfromrefug** [Lokavaluto/lokavaluto-addons#84]
It would be good to have a POST parameter 
```typescript
categories?:string[];
```
that would allow to filter (and thus smaller request) by categories

**Comment by farfromrefug** [comment]
Actually following that discussion we also need an API to return the list for available categories.

**Comment by stephansainleger** [comment]
New API service which returns the partner industries list : https://odoo12.dev.lokavaluto.fr/api-docs?urls.primaryName=lokavaluto_api%2Fpublic%3A%20partner_industry

Example script added in lokavaluto-mobile-application repository : https://github.com/Lokavaluto/lokavaluto-mobile-application/blob/master/lokavaluto/scripts/script_test_get_partner_industries.mjs

**Comment by stephansainleger** [comment]
Filter on the search_by_area service by category is now available : https://odoo12.dev.lokavaluto.fr/api-docs?urls.primaryName=lokavaluto_api%2Fpublic%3A%20partner_map#/default/post_search_in_area

**WARNING : the input `category` is mandatory, but the value can be empty (then we look for all the categories)**

Example script updated with a test scenario : https://github.com/Lokavaluto/lokavaluto-mobile-application/blob/master/lokavaluto/scripts/script_test_get_partners_in_area.mjs

**Comment by stephansainleger** [comment]
Now possible to filter on several categories, send in a JSON list : https://odoo12.dev.lokavaluto.fr/api-docs?urls.primaryName=lokavaluto_api%2Fpublic%3A%20partner_map#/default/post_search_in_area

**Comment by stephansainleger** [comment]
**API service partner_industry :**
- service name has changed, it is now `get` instead of `get_all`
- possible to filter on industry ids, with an optional list of integers in input of the GET request

**Comment by njeudy** [comment]
can close this one ? feel free to reopen if needed
